[theme]
primaryColor="#2E5FA7"        # Azul corporativo IBA
backgroundColor="#FFFFFF"     # Blanco limpio
secondaryBackgroundColor="#F0F2F6"  # Gris claro
textColor="#2CA46C"           # Verde PNU para resaltar
font="sans serif"
